# CircleCI configuration file
version: 2.1

jobs:
  # Build
  build:
    docker:
     - image: cimg/base:2022.05
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: cmake -Bbuild ./
      - run: (cd ./build && make)
      - run: pwd
      - run: ls
  # Test
  test:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: ./build/test

workflows:
  build_and_test:
    jobs:
      - build
      - test