# CircleCI configuration file
version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/base:2022.05
    working_directory: ./

jobs:
  # Build
  build:
    executor: my-executor
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: cmake -Bbuild ./
      - run: (cd ./build && make)
      - run: pwd
      - run: ls
      - persist_to_workspace:
          root: workspace
          paths:
            - ./build/test
  # Test
  test:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /workspace
      - run: pwd
      - run: ls
      - run: ls /workspace
      - run: ls /workspace/build
      - run: /workspace/build/test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
