# CircleCI configuration file
version: 2.1

jobs:
  # Build
  build:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: pwd
      - run: ls
      - run: cmake -Bbuild ./
      - run: cd build
      - run: make
      - run: cd ..
  # Test
  test:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: build/test

workflows:
  build_and_test:
    jobs:
      - build
      - test