# CircleCI configuration file
version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/base:2022.05

jobs:
  # Build
  build:
    executor: my-executor
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: cmake -Bbuild ./
      - run: (cd ./build && make)
      - persist_to_workspace:
          root: build
          paths:
            - test

  # Test
  test:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ./
      - run: ./test --gtest_output=xml
      - store_test_results:
          path: ./

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
