# CircleCI configuration file
version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/base:2022.05

jobs:
  # Build
  build:
    executor: my-executor
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: cmake -Bbuild ./
      - run: (cd ./build && make)
      - run: pwd
      - run: ls
      - run: ls /build
      - run: /build/test
  # Test
  test:
    executor: my-executor
    steps:
      - run: pwd
      - run: ls

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
